CandyShop_engine/CandyShop_engine/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import register
from django.contrib.auth.views import (
    LoginView,
    LogoutView
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('register/', register, name='register_url'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login_url'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout_url'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CandyShop_engine/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart_detail_url'),
    path('add/<int:id>', cart_add, name='cart_add_url'),
    path('remove/<int:id>', cart_remove, name='cart_remove_url'),
]

CandyShop_engine/orders/urls.py
from django.urls import path
from .views import order_create


app_name = 'orders'
urlpatterns = [
    path('create/', order_create, name='order_create_url'),
]

CandyShop_engine/shop/urls.py
from django.urls import path
from .views import (
    CandyList,
    CandyDetail,
    CurrentCandyList,
)

app_name = 'shop'
urlpatterns = [
    path('', CandyList.as_view(), name='candy_list_url'),
    path('<int:pk>/detail/', CandyDetail.as_view(), name='candy_detail_url'),
    path('candy/<int:pk>', CurrentCandyList.as_view(), name='current_candy_list_url'),
]

CandyShop_engine/cart/models.py
from django.db import models

# Create your models here.

CandyShop_engine/cart/forms.py
from django import forms

PRODUCT_COUNT_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    count = forms.TypedChoiceField(choices=PRODUCT_COUNT_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

CandyShop_engine/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Candy
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, id):
    cart = Cart(request)
    product = get_object_or_404(Candy, id=id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart.add(product=product,
                 count=form.cleaned_data['count'],
                 update_count=form.cleaned_data['update'])

    return redirect('cart:cart_detail_url')


def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Candy, id=id)
    cart.remove(product)
    return redirect('cart:cart_detail_url')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', context={'cart': cart})

CandyShop_engine/cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
    <h1>Your shopping cart</h1>
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.count }}</td>
                    <td><a href="{% url "cart:cart_remove_url" product.id %}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:candy_list_url" %}" class="btn btn-primary">Continue shopping</a>
        <a href="{% url 'orders:order_create_url' %}" class="btn btn-success">Checkout</a>
    </p>
{% endblock %}