CandyShop_engine/CandyShop_engine/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import register
from django.contrib.auth.views import (
    LoginView,
    LogoutView
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('register/', register, name='register_url'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login_url'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout_url'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CandyShop_engine/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart_detail_url'),
    path('add/<int:id>', cart_add, name='cart_add_url'),
    path('remove/<int:id>', cart_remove, name='cart_remove_url'),
]

CandyShop_engine/shop/urls.py
from django.urls import path
from .views import (
    CandyList,
    CandyDetail,
    CurrentCandyList,
)

app_name = 'shop'
urlpatterns = [
    path('', CandyList.as_view(), name='candy_list_url'),
    path('<int:pk>/detail/', CandyDetail.as_view(), name='candy_detail_url'),
    path('candy/<int:pk>', CurrentCandyList.as_view(), name='current_candy_list_url'),
]

CandyShop_engine/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'shop/main.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <title>
        {% block title %}
            Main title
        {% endblock %}
    </title>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url "shop:candy_list_url" %}">Candy Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:candy_list_url' %}">Catalog<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail_url' %}">Cart</a>
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "login_url" %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "register_url" %}">Register</a>
                </li>
            {% endif %}

            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "logout_url" %}">Logout</a>
                </li>
                <li class="nav-item">
                    <span class="nav-link ml-5 text-success">Current user is: {{ user.username }}</span>
                </li>
            {% endif %}

        </ul>
    </div>
    <div class="navbar-nav">
        {% with total_items=cart|length %}
            {% if cart|length > 0 %}
                Your cart:
                <a href="{% url 'cart:cart_detail_url' %}">{{ total_items }} item{{ total_items|pluralize }},
                    ${{ cart.get_total_price }}
                </a>
            {% else %}
                Your cart is empty.

            {% endif %}
        {% endwith %}
    </div>
</nav>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        {% block sidebar %}
            <div class="col-md-4">
                <div class="content-section">
                    {% block sidebar_content %}

                    {% endblock %}
                </div>
            </div>
        {% endblock %}
    </div>
</main>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>


</body>
</html>