CandyShop_engine/CandyShop_engine/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import register
from django.contrib.auth.views import (
    LoginView,
    LogoutView
)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('register/', register, name='register_url'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login_url'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout_url'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CandyShop_engine/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart_detail_url'),
    path('add/<int:id>', cart_add, name='cart_add_url'),
    path('remove/<int:id>', cart_remove, name='cart_remove_url'),
]

CandyShop_engine/shop/urls.py
from django.urls import path
from .views import (
    CandyList,
    CandyDetail,
    CurrentCandyList,
)

app_name = 'shop'
urlpatterns = [
    path('', CandyList.as_view(), name='candy_list_url'),
    path('<int:pk>/detail/', CandyDetail.as_view(), name='candy_detail_url'),
    path('candy/<int:pk>', CurrentCandyList.as_view(), name='current_candy_list_url'),
]

CandyShop_engine/shop/models.py
from django.db import models


class CandyType(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.title}'


class Candy(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(default=5000, max_digits=10, decimal_places=2)
    type = models.ForeignKey('CandyType', on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='candy_pics')

    def __str__(self):
        return f'{self.name}'

CandyShop_engine/shop/forms.py
from django import forms

CandyShop_engine/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    ListView,
    DetailView,
)
from .models import Candy, CandyType
from django.contrib.auth.models import User
from cart.forms import CartAddProductForm


class CandyList(ListView):
    model = Candy
    template_name = 'shop/index.html'
    context_object_name = 'candys'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        types = CandyType.objects.all()
        context['types'] = types
        return context


class CurrentCandyList(ListView):
    model = Candy
    template_name = 'shop/current_candy_list.html'
    context_object_name = 'candys'
    paginate_by = 2

    def get_queryset(self):
        candy_type = get_object_or_404(CandyType, pk=self.kwargs.get('pk'))
        return Candy.objects.filter(type=candy_type)


class CandyDetail(DetailView):
    model = Candy
    template_name = 'shop/candy_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CartAddProductForm()
        return context

CandyShop_engine/shop/templates/shop/candy_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    {{ object.name }}
{% endblock %}

{% block content %}
    <article class="media content-section">
        {#        <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}" alt="">#}
        <div class="media-body">
            <div>
                <form action="{% url 'cart:cart_add_url' id=candy.id%}" method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form|crispy }}
                    </fieldset>
                    <input type="submit" class="btn btn-outline-primary btn-sm mt-1 mb-1" value="Add To Cart">
                </form>
            </div>
            <h2 class="article-title">{{ object.name }}</h2>
            <p class="article-content">{{ object.description }}</p>
        </div>
    </article>
{% endblock %}


{% block sidebar %}
{% endblock %}

CandyShop_engine/shop/templates/shop/current_candy_list.html
{% extends 'base.html' %}
{% block title %}
    CandyShop
{% endblock %}

{% block content %}
    {% for candy in candys %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ candy.image.url }}" alt="">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="">{{ candy.type.title }}</a>
                    <small class="text-muted"></small>
                </div>
                <h2><a class="article-title" href="{% url 'shop:candy_detail_url' pk=candy.pk %}">{{ candy.name }}</a>
                </h2>
                <p class="article-content">{{ candy.description }}</p>
            </div>
        </article>
    {% endfor %}

{% endblock %}

{% block sidebar %}
    <div class="col-md-4">
        <div class="content-section">
            <h3>Candy Types</h3>
            <p class='text-muted'>
                <a href="{% url "shop:candy_list_url" %}" class="list-group-item list-group-item-light">All</a>
            </p>
        </div>
    </div>
    {% if is_paginated %} <!-- это из MultipleObjectMixin -->

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}<!-- page_obj.number|add:'3' означает page_obj.number + 3 -->
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}

        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock %}

{% block sidebar_content %}

{% endblock %}

CandyShop_engine/shop/templates/shop/index.html
{% extends 'base.html' %}
{% block title %}
    CandyShop
{% endblock %}

{% block content %}
    {% for candy in candys %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ candy.image.url }}" alt="">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2"
                       href="{% url 'shop:current_candy_list_url' pk=candy.type.pk %}">{{ candy.type.title }}</a>
                    <small class="text-muted"></small>
                </div>
                <h2><a class="article-title" href="{% url 'shop:candy_detail_url' pk=candy.pk %}">{{ candy.name }}</a>
                </h2>
                <p class="article-content">{{ candy.description }}</p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %} <!-- это из MultipleObjectMixin -->

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}<!-- page_obj.number|add:'3' означает page_obj.number + 3 -->
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}

        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}

{% endblock %}

{% block sidebar_content %}
    <h3>Candy Types</h3>
    <p class='text-muted'>
    <ul class="list-group">

        {% for type in types %}
            <a href="{% url "shop:current_candy_list_url" pk=type.id %}"
               class="list-group-item list-group-item-light">{{ type }}</a>
        {% endfor %}

    </ul>
    </p>
{% endblock %}